[package]
name = "parapet"
version = "0.1.0"
authors = ["Spencer Powell <krornus@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21"
time = "0.1"
xcb = { version = "0.8", features = ["randr"] }

[dev-dependencies]
memmap = "0.7.0"
